#!/bin/bash
rm /usr/bin/gcc
ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
rm /usr/bin/g++
ln -s /usr/bin/g++-4.9 /usr/bin/g++
rm /usr/bin/c++
ln -s /usr/bin/g++-4.9 /usr/bin/c++
rm /usr/bin/cc
ln -s /usr/bin/gcc-4.9 /usr/bin/cc
