#!/bin/bash
myrepo=$1

echo "removing files from target locations"
rm ~/.bashrc
rm ~/.conkyrc
rm ~/.gitignore
rm ~/.vimrc
rm ~/toGcc*
rm ~/dev/${myrepo}/.git/hooks/pre-commit

cd ~
echo "link to gcc copying files"
#ln -sfn dev/tools/setup/toGcc52 toGcc52
#ln -sfn dev/tools/setup/toGcc49 toGcc49
echo "setup link to .bashrc"
ln -sfn dev/tools/setup/.bashrc .bashrc
echo "setup link to .conkyrc"
ln -sfn dev/tools/setup/.conkyrc .conkyrc
echo "setup link to .gitignore"
ln -sfn dev/tools/setup/.gitignore .gitignore
echo "setup link to .vimrc"
ln -sfn dev/tools/setup/.vimrc .vimrc

rm /usr/bin/clang-format
ln -sfn /opt/externpro/externpro-15.10.2-gcc49-64-Linux/bin/clang-format /usr/bin/clang-format
ln -sfn /usr/bin/clang-tidy-3.7 /usr/bin/clang-tidy
ln -sfn /usr/bin/clang-check-3.7 /usr/bin/clang-check

#echo "setup link to pre-commit hook in repo"
#cd ~/dev/${myrepo}/.git/hooks
#ln -sfn ~/dev/tools/setup/pre-commit pre-commit

ln -sfn ~/dev/tools/setup/git-completion.bash git-completion.bash
echo "linked tools to locations"
